### ISSUE TITLE
Widget is broken in 7.12 Atlas UI

### ISSUE THREAD

**Issue by DblTS** [cdcharlebois/DatePair#11]
The widget seems broken in 7.12 + Atlas UI:
-- When display as modal is true, it does pop up, but behaviour in UI is undesired
-- When display as modal is false, it does not show at all.

Please find reproduction project attached.
https://wetransfer.com/downloads/1c99d17067524b0570d793c95349ba9220180309091409/d40921f2038344ac57bf959c55c2981c20180309091409/9b502b

**Comment by cdcharlebois** [comment]
Thanks for bringing this up and the helpful test project. I'll look into this next week

**Comment by cdcharlebois** [comment]
this issue is now resolves in v2.0.0 https://github.com/cdcharlebois/DatePair/releases/tag/2.0.0 

Thanks!
